version: "test-{build}"
environment:
    matrix:
        - nodejs_version: "18"
        - nodejs_version: "20"
        - nodejs_version: "22"
platform:
    - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
    - ps: "Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform"
    - ps: "$NpmVersion = (npm -v).Substring(0,1)"
    - npm install
test_script:
    - echo %cd%
    - node --version
    - npm --version
    - npm test
build: "off"
