/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"tibberlink adapter settings": {
		en: "Adapter settings for tibberlink",
		de: "Adaptereinstellungen für tibberlink",
		ru: "Настройки адаптера для tibberlink",
		pt: "Configurações do adaptador para tibberlink",
		nl: "Adapterinstellingen voor tibberlink",
		fr: "Paramètres d'adaptateur pour tibberlink",
		it: "Impostazioni dell'adattatore per tibberlink",
		es: "Ajustes del adaptador para tibberlink",
		pl: "Ustawienia adaptera dla tibberlink",
		"zh-cn": "tibberlink",
	},
	TibberAPIToken: {
		en: "token for tibber api",
		de: "Token für Tibber API",
		ru: "токен для tibber api",
		pt: "token para tibber api",
		nl: "Token voor Tibber API",
		fr: "jeton pour tibber api",
		it: "token per tibber api",
		es: "token for tibber api",
		pl: "znajdował się w dżibli apib",
		uk: "токен для tibber api",
		"zh-cn": "浮动",
	},
	PulseActive: {
		en: "use tibber pulse (all homes)",
		de: "Tibber Pulse verwenden (alle Zuhause)",
		ru: "использовать tibber импульс (все дома)",
		pt: "usar pulso de tibber (todas as casas)",
		nl: "gebruik kietel pols",
		fr: "utiliser l'impulsion de tibber (toutes les maisons)",
		it: "usare il polso del tibber (tutte le case)",
		es: "use pulso de tibber (todas las casas)",
		pl: "użycie impulsu (wszystkie domy)",
		uk: "використовувати tibber імпульс (всі будинки)",
		"zh-cn": "1. 使用季节(所有住房)",
	},
	SelectFieldsForFeed: {
		en: "Select all fields you want to load in feed data (power and timestamp are default):",
		de: "Wählen Sie alle Felder, die beim Abruf der Live Messung abgerufen werden sollen (Power und Zeitstempel sind per Standard enthalten):",
		ru: "Выберите все поля, которые вы хотите загрузить в данных корма (сила и метка по умолчанию):",
		pt: "Selecione todos os campos que você deseja carregar em dados de feed (poder e timestamp são padrão):",
		nl: "Selecteer alle velden die je wilt laden in voedingsgegevens",
		fr: "Sélectionnez tous les champs que vous souhaitez charger dans les données d'alimentation (puissance et timetamp sont par défaut):",
		it: "Selezionare tutti i campi che si desidera caricare nei dati di alimentazione (potenza e timestamp sono di default):",
		es: "Seleccione todos los campos que desea cargar en los datos de alimentación (la potencia y el temporizador son predeterminados):",
		pl: "Wybrane wszystkie pola, które chcemy załadować dane karmiące (potrzebowanie na czas) są domyślne",
		uk: "Виберіть всі поля, які ви хочете завантажити в живих даних (потужність та час) за замовчуванням:",
		"zh-cn": "离开你想装载饲料数据的所有领域(权力和时间包):",
	}
};
